default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: anything_development
  username: mvp
  password: mvp123

test:
  <<: *default
  host: localhost
  database: anything_test
  username: mvp
  password: mvp123

production:
  <<: *default
  database: db/production.sqlite3
