# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Vendor.create(vendor_company: "Kumpulan Saintifik FE Sdn Bhd")


Category.create(category_name:"glassware")
category = Category.first

category.subcategories.create(subcategory_name:"beaker")
category.subcategories.create(subcategory_name:"burette")
category.subcategories.create(subcategory_name:"cylinder")
category.subcategories.create(subcategory_name:"flask")
category.subcategories.create(subcategory_name:"volumetric flask")



Product.create(product_name: "Pyrex Low Form Beaker", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 3819 and DIN 12331</li><li>Manufactured from Pyrex borosilicate glass</li><li>Excellent thermal performance</li><li>High resistance to chemical attack</li><li>White graduations and marking spot</li></ul>", category_id: "1", subcategory_id:"1", vendor_id:"1")
product = Product.find(1)
product.variations.create(variation_name: "5 ml", variation_sku: "KSFE-1000/03M", variation_price: "11.00")
product.variations.create(variation_name: "10 ml", variation_sku: "KSFE-1000/05M", variation_price: "13.00")
product.variations.create(variation_name: "25 ml", variation_sku: "KSFE-1000/11M", variation_price: "10.00")
product.variations.create(variation_name: "50 ml", variation_sku: "KSFE-1000/02M", variation_price: "10.00")
product.variations.create(variation_name: "100 ml", variation_sku: "KSFE-1000/04D", variation_price: "9.00")
product.variations.create(variation_name: "150 ml", variation_sku: "KSFE-1000/06D", variation_price: "12.00")
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE-1000/10D", variation_price: "12.00")
product.variations.create(variation_name: "400 ml", variation_sku: "KSFE-1000/14D", variation_price: "14.00")
product.variations.create(variation_name: "600 ml", variation_sku: "KSFE-1000/18D", variation_price: "16.00")
product.variations.create(variation_name: "800 ml", variation_sku: "KSFE-1000/20D", variation_price: "24.00")
product.variations.create(variation_name: "1000 ml", variation_sku: "KSFE-1000/22D", variation_price: "2.00")
product.variations.create(variation_name: "2000 ml", variation_sku: "KSFE-1000/28D", variation_price: "47.00")
product.variations.create(variation_name: "3000 ml", variation_sku: "KSFE-1000/30D", variation_price: "79.00")
product.variations.create(variation_name: "5000 ml", variation_sku: "KSFE-1000/34D", variation_price: "149.00")
product.variations.create(variation_name: "10000 ml", variation_sku: "KSFE-1000/38D", variation_price: "705.00")

Product.create(product_name: "Pyrex Low Form Heavy Duty Beaker", product_brand: "Pyrex", product_description: "<ul><li>Mechanically stronger than standard beakers</li><li>Designed for longer life and increased user safety</li><li>Reinforced rims and spout, less prone to breakage during washing etc.</li><li>Thicker walls and heavier bases</li><li>Manufactured from Pyrex borosilicate glass</li><li>White graduations and marking spot</li></ul>", category_id: "1", subcategory_id:"1", vendor_id:"1")
product = Product.find(2)
product.variations.create(variation_name: "150 ml", variation_sku: "KSFE-1003-150", variation_price: "19.00")
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE-1003-250", variation_price: "19.00")
product.variations.create(variation_name: "400 ml", variation_sku: "KSFE-1003-400", variation_price: "24.00")
product.variations.create(variation_name: "600 ml", variation_sku: "KSFE-1003-600", variation_price: "28.00")
product.variations.create(variation_name: "800 ml", variation_sku: "KSFE-1003-800", variation_price: "54.00")
product.variations.create(variation_name: "1000 ml", variation_sku: "KSFE-1003-1L", variation_price: "111.00")
product.variations.create(variation_name: "2000 ml", variation_sku: "KSFE-1003-2L", variation_price: "313.00")
product.variations.create(variation_name: "5000 ml", variation_sku: "KSFE-1003-5L", variation_price: "217.00")

Product.create(product_name: "Pyrex Tall Form Beaker", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 3819 and DIN 12331</li><li>Manufactured from Pyrex borosilicate glass</li><li>Tall form with spout</li><li>White graduations and marking spot</li></ul>", category_id: "1", subcategory_id:"1", vendor_id:"1")
product = Product.find(3)
product.variations.create(variation_name: "50 ml", variation_sku: "KSFE/02M", variation_price: "10.00")
product.variations.create(variation_name: "100 ml", variation_sku: "KSFE/04D", variation_price: "10.00")
product.variations.create(variation_name: "150 ml", variation_sku: "KSFE/06D", variation_price: "12.00")
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE/10D", variation_price: "13.00")
product.variations.create(variation_name: "400 ml", variation_sku: "KSFE/14D", variation_price: "14.00")
product.variations.create(variation_name: "600 ml", variation_sku: "KSFE/18D", variation_price: "17.00")
product.variations.create(variation_name: "1000 ml", variation_sku: "KSFE/22D", variation_price: "27.00")
product.variations.create(variation_name: "2000 ml", variation_sku: "KSFE/26D", variation_price: "49.00")

Product.create(product_name: "Pyrex Conical Form Beaker", product_brand: "Pyrex", product_description: "<ul><li>Conical shape (Phillips pattern) with spout</li><li>Manufactured from Pyrex borosilicate glass</li><li>Excellent thermal performance and chemical resistance</li></ul>", category_id: "1", subcategory_id:"1", vendor_id:"1")
product = Product.find(4)
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE-1020/06D", variation_price: "26.00")
product.variations.create(variation_name: "500 ml", variation_sku: "KSFE-1020/16D", variation_price: "43.00")

Product.create(product_name: "Pyrex Jacketed Beaker", product_brand: "Pyrex", product_description: "<ul><li>Useful for maintaining samples at a constant temperature</li><li>With integral jacket through which a teperature controlling medium can be circulated</li><li>Manufactured from heat resistant Pyrex borosilicate glass</li><li>With PTFE screwthread connectors for simple and safe connection of 9mm bore tubing</li></ul>", category_id: "1", subcategory_id:"1", vendor_id:"1")
product = Product.find(5)
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE-1025/10SC", variation_price: "568.00")
product.variations.create(variation_name: "600 ml", variation_sku: "KSFE-1025/18SC", variation_price: "668.00")
product.variations.create(variation_name: "1000 ml", variation_sku: "KSFE-1025/22SC", variation_price: "750.00")
product.variations.create(variation_name: "2000 ml", variation_sku: "KSFE-1025/28SC", variation_price: "960.00")

Product.create(product_name: "Pyrex PTFE key, class AS (works certified) Burette", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 385</li><li>Individually tested and supplied with cerrtificate showing exact volume dispensed at 3 points on the scale</li><li>Individual serial number and cerrtificate provides complete traceability to National Standards</li><li>Each burette has a +30s waiting time before final reading can be taken</li><li>Manufactured from precision-bore borosilicate glass tubing for high accuracy</li><li>1.5mm bore PTFE key which requires no lubrication</li><li>White enamel graduations</li><li>White enamel graduations</li></ul>", category_id: "1", subcategory_id:"2", vendor_id:"1")
product = Product.find(6)
product.variations.create(variation_name: "10 ml - graduations 0.02 ml", variation_sku: "KSFE-3295/22ASWC", variation_price: "227.00" )
product.variations.create(variation_name: "25 ml - graduations 0.10 ml", variation_sku: "KSFE-3295/24ASWC", variation_price: "203.00")
product.variations.create(variation_name: "50 ml - graduations 0.10 ml", variation_sku: "KSFE-3295/26ASWC", variation_price: "207.00")
product.variations.create(variation_name: "100 ml - graduations 0.20 ml", variation_sku: "KSFE-3295/28ASWC", variation_price: "251.00")

Product.create(product_name: "Pyrex PTFE key, class AS Burette", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 385</li><li>Manufactured from precision-bore borosilicate glass tubing for high accuracy</li><li>Each burette has a +30s waiting time before final reading can be taken</li><li>Graduations in white enamel for increased visibility with dark solutions</li><li>Grease-free interchangable PTFE key with 1.5mm bore</li></ul>", category_id: "1", subcategory_id:"2", vendor_id: "1")
product = Product.find(7)
product.variations.create(variation_name: "10 ml - graduations 0.02 ml", variation_sku: "KSFE-3295/12AS", variation_price: "153.00")
product.variations.create(variation_name: "25 ml - graduations 0.10 ml", variation_sku: "KSFE-3295/14AS", variation_price: "129.00")
product.variations.create(variation_name: "50 ml - graduations 0.10 ml", variation_sku: "KSFE-3295/16AS", variation_price: "137.00")
product.variations.create(variation_name: "100 ml - graduations 0.20 ml", variation_sku: "KSFE-3295/18AS", variation_price: "178.00")

Product.create(product_name: "Pyrex PTFE key, class AS Schellbach Burette", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 385</li><li>Graduations and inscriptions in blue enamel</li>Shellbach burette tube with vertical white stripe and centra blue ribbon<li>Facilitates accuraate reading of meniscus</li><li>exact position of the meniscus is clearly defined where the blue ribbon splits into a wide and narrow band</li></li><li>With funnel top to make filling easier and safer</li><li>Each burette has a +30s waiting time before final reading can be taken</li><li>Manufactured from chemical resistance borosilicate</li><li>Grease-free interchangable PTFE key with 1.5mm bore</li></ul>", category_id: "1", subcategory_id:"2", vendor_id: "1")
product = Product.find(8)
product.variations.create(variation_name: "10 ml - graduations 0.05 ml", variation_sku: "KSFE-492092", variation_price: "169.00")
product.variations.create(variation_name: "25 ml - graduations 0.10 ml", variation_sku: "KSFE-492093", variation_price: "169.00")
product.variations.create(variation_name: "25 ml - graduations 0.05 ml", variation_sku: "KSFE-492094", variation_price: "169.00")
product.variations.create(variation_name: "50 ml - graduations 0.10 ml", variation_sku: "KSFE-492095", variation_price: "205.00")

Product.create(product_name: "MBL PTFE key, Burette Class B", product_brand: "MBL", product_description: "<ul><li>Complies with ISO 385</li><li>10, 25 and 50 ml sizes are availabile fitted with funnel top to make filling easier and safer</li><li>Grease-free PTFE stopcock with 1.5mm bore</li><li>Graduations in easy to read blue enamel</li></ul>", category_id: "1", subcategory_id:"2", vendor_id: "1")
product = Product.find(9)
product.variations.create(variation_name: "10 ml - graduations 0.02 ml", variation_sku: "KSFE-BRB070P", variation_price: "169.00")
product.variations.create(variation_name: "25 ml - graduations 0.10 ml", variation_sku: "KSFE-BRB074P", variation_price: "169.00")
product.variations.create(variation_name: "25 ml - graduations 0.10 ml", variation_sku: "KSFE-BRB075P", variation_price: "169.00")
product.variations.create(variation_name: "50 ml - graduations 0.10 ml", variation_sku: "KSFE-BRB076P", variation_price: "205.00")
product.variations.create(variation_name: "50 ml - graduations 0.10 ml", variation_sku: "KSFE-BRB077P", variation_price: "205.00")

Product.create(product_name: "MBL PTFE key, Rotaflo, Burette Class B", product_brand: "MBL", product_description: "<ul><li>Complies with ISO 385</li><li>With GP Rotoflo stopcock having PTFE key<li>No lubrication required</li><li>No seizure with caustic solutions</li><li>Provides fine drop control</li><li>3.0mm key bore</li></li><li>Graduations in permanent amber stain which is fused into the glass and is especially resistant to aggresive cleaning solutions</li><li>Manufactured from borosilicate glass</li></ul>", category_id: "1", subcategory_id:"2", vendor_id: "1")
product = Product.find(10)
product.variations.create(variation_name: "10 ml - graduations 0.10 ml", variation_sku: "KSFE-BRB402", variation_price: "169.00")
product.variations.create(variation_name: "25 ml - graduations 0.10 ml", variation_sku: "KSFE-BRB404", variation_price: "169.00")
product.variations.create(variation_name: "50 ml - graduations 0.10 ml", variation_sku: "KSFE-BRB406", variation_price: "205.00")
product.variations.create(variation_name: "100 ml - graduations 0.20 ml", variation_sku: "KSFE-BRB408", variation_price: "205.00")

Product.create(product_name: "Pyrex Cylinder, with spout, class A, works certified", product_sku: "", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 4788</li><li>Caolibrated to Class A tolerances</li><li>Individually tested and supplied with certificate showing exact volume contained at 5 points on the scale</li><li>Conformity 'H' certified</li><li>Inscribed with individual serial number for batch certification</li><li>Graduation in white enamel</li><li>Manufactured from chemically resistant borosilicate glass with hexagonal foot</li></ul>", category_id: "1", subcategory_id:"3", vendor_id: "1")
product = Product.find(11)
product.variations.create(variation_name: "5 ml - graduations 0.1 ml", variation_sku: "KSFE-3201/02WC", variation_price: "185.00")
product.variations.create(variation_name: "10 ml - graduations 0.2 ml", variation_sku: "KSFE-3201/04WC", variation_price: "185.00")
product.variations.create(variation_name: "25 ml - graduations 0.5 ml", variation_sku: "KSFE-320106WC", variation_price: "202.00")
product.variations.create(variation_name: "50 ml - graduations 1 ml", variation_sku: "KSFE-3201/08WC", variation_price: "206.00")
product.variations.create(variation_name: "100 ml - graduations 1 ml", variation_sku: "KSFE-3201/10WC", variation_price: "214.00")
product.variations.create(variation_name: "250 ml - graduations 2 ml", variation_sku: "KSFE-3201/12WC", variation_price: "257.00")
product.variations.create(variation_name: "500 ml - graduations 5 ml", variation_sku: "KSFE-3201/14WC", variation_price: "318.00")
product.variations.create(variation_name: "1000 ml - graduations 10 ml", variation_sku: "KSFE-3201/16WC", variation_price: "362.00")
product.variations.create(variation_name: "2000 ml - graduations 20 ml", variation_sku: "KSFE-3201/18WC", variation_price: "519.00")

Product.create(product_name: "Pyrex Cylinder, with spout, class A", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 4788</li><li>Calibrated to Class A tolerances</li><li>Conformity 'H' certified</li><li>Inscribed with for batch certificate</li><li>Graduation in white enamel</li><li>Manufactured from chemically resistant borosilicate glass with hexagonal foot</li></ul>", category_id: "1", subcategory_id:"3", vendor_id: "1")
product = Product.find(12)
product.variations.create(variation_name: "5 ml - graduations 0.1 ml", variation_sku: "KSFE-3201/02", variation_price: "43.00")
product.variations.create(variation_name: "10 ml - graduations 0.2 ml", variation_sku: "KSFE-3201/04", variation_price: "42.00")
product.variations.create(variation_name: "25 ml - graduations 0.5 ml", variation_sku: "KSFE-320106", variation_price: "33.00")
product.variations.create(variation_name: "50 ml - graduations 1 ml", variation_sku: "KSFE-3201/08", variation_price: "37.00")
product.variations.create(variation_name: "100 ml - graduations 1 ml", variation_sku: "KSFE-3201/10", variation_price: "41.00")
product.variations.create(variation_name: "250 ml - graduations 2 ml", variation_sku: "KSFE-3201/12", variation_price: "57.00")
product.variations.create(variation_name: "500 ml - graduations 5 ml", variation_sku: "KSFE-3201/14", variation_price: "85.00")
product.variations.create(variation_name: "1000 ml - graduations 10 ml", variation_sku: "KSFE-3201/16", variation_price: "115.00")
product.variations.create(variation_name: "2000 ml - graduations 20 ml", variation_sku: "KSFE-3201/18", variation_price: "217.00")

Product.create(product_name: "Pyrex Round Bottom Narrow Neck Flask", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 1773</li><li>Manufactured from Pyrex borosilicate glass which offers excellent resistance to chemical corrosion and thermal shock</li></ul>", category_id: "1", subcategory_id:"4", vendor_id: "1")
product = Product.find(13)
product.variations.create(variation_name: "50 ml", variation_sku: "KSFE-1100/02M", variation_price: "29.00")
product.variations.create(variation_name: "100 ml", variation_sku: "KSFE-1100/04M", variation_price: "16.00")
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE-1100/12D", variation_price: "16.00")
product.variations.create(variation_name: "500 ml", variation_sku: "KSFE-1100/18D", variation_price: "22.00")
product.variations.create(variation_name: "1000 ml", variation_sku: "KSFE-1100/24D", variation_price: "32.00")
product.variations.create(variation_name: "2000 ml", variation_sku: "KSFE-1100/28D", variation_price: "89.00")
product.variations.create(variation_name: "4000 ml", variation_sku: "KSFE-1100/32D", variation_price: "169.00")
product.variations.create(variation_name: "6000 ml", variation_sku: "KSFE-1100/35D", variation_price: "277.00")
product.variations.create(variation_name: "10000 ml", variation_sku: "KSFE-1100/36D", variation_price: "585.00")
product.variations.create(variation_name: "20000 ml", variation_sku: "KSFE-1100/38D", variation_price: "927.00")

Product.create(product_name: "Pyrex Round Bottom Wide Neck Flask", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 24450 and DIN 12353</li><li>With wide neck to facilitate addition of solid samples etc.</li><li>Pyrex glass means highest resistance to chemical corrosion and thermal shock</li></ul>", category_id: "1", subcategory_id:"4", vendor_id: "1")
product = Product.find(14)
product.variations.create(variation_name: "100 ml", variation_sku: "KSFE-1120/04M", variation_price: "16.00")
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE-1120/08D", variation_price: "58.00")
product.variations.create(variation_name: "500 ml", variation_sku: "KSFE-1120/14D", variation_price: "28.00")
product.variations.create(variation_name: "1000 ml", variation_sku: "KSFE-1120/18D", variation_price: "45.00")
product.variations.create(variation_name: "2000 ml", variation_sku: "KSFE-1120/22D", variation_price: "203.00")
product.variations.create(variation_name: "4000 ml", variation_sku: "KSFE-1120/26D", variation_price: "406.00")
product.variations.create(variation_name: "6000 ml", variation_sku: "KSFE-1120/29D", variation_price: "370.00")

Product.create(product_name: "Pyrex Round Flat Narrow Neck Flask", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 1773</li><li>Flat base for standing on benches and hotplates etc.</li><li>Manufactured from Pyrex glass for high resistance to thermal shock</li><li>Excellent chemical durability for contamination-free performance</li><li>With white enamel marking spot</li></ul>", category_id: "1", subcategory_id:"4", vendor_id: "1")
product = Product.find(15)
product.variations.create(variation_name: "50 ml", variation_sku: "KSFE-1070/02M", variation_price: "35.00")
product.variations.create(variation_name: "100 ml", variation_sku: "KSFE-1070/04M", variation_price: "15.00")
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE-1070/12D", variation_price: "16.00")
product.variations.create(variation_name: "500 ml", variation_sku: "KSFE-1070/18D", variation_price: "22.00")
product.variations.create(variation_name: "1000 ml", variation_sku: "KSFE-1070/24D", variation_price: "30.00")
product.variations.create(variation_name: "2000 ml", variation_sku: "KSFE-1070/28D", variation_price: "88.00")
product.variations.create(variation_name: "4000 ml", variation_sku: "KSFE-1070/32D", variation_price: "277.00")
product.variations.create(variation_name: "6000 ml", variation_sku: "KSFE-1070/36D", variation_price: "400.00")
product.variations.create(variation_name: "10000 ml", variation_sku: "KSFE-1070/38D", variation_price: "595.00")
product.variations.create(variation_name: "12000 ml", variation_sku: "KSFE-1070/40D", variation_price: "566.00")
product.variations.create(variation_name: "20000 ml", variation_sku: "KSFE-1070/42D", variation_price: "987.00")

Product.create(product_name: "Pyrex Flat Bottom Wide Neck Flask", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 24450 and DIN 12353</li><li>With wide neck to facilitate addition of solid samples etc.</li><li>Flat base for standing on benches and hotplates etc.</li><li>Manufactured from Pyrex glass for high resistance to thermal shock</li><li>Excellent chemical durability for contamination-free performance</li></ul>", category_id: "1", subcategory_id:"4", vendor_id: "1")
product = Product.find(16)
product.variations.create(variation_name: "50 ml", variation_sku: "KSFE-1080/02M", variation_price: "46.00")
product.variations.create(variation_name: "100 ml", variation_sku: "KSFE-1080/04M", variation_price: "17.00")
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE-1080/08D", variation_price: "19.00")
product.variations.create(variation_name: "500 ml", variation_sku: "KSFE-1080/10D", variation_price: "34.00")
product.variations.create(variation_name: "1000 ml", variation_sku: "KSFE-1080/12D", variation_price: "64.00")
product.variations.create(variation_name: "2000 ml", variation_sku: "KSFE-1080/24D", variation_price: "165.00")

Product.create(product_name: "Pyrex Narrow Neck Conical Flask", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 1773 and DIN 12353</li><li>Erlenmeyer pattern</li><li>Manufactured from Pyrex borosilicate glass for highest resistance to thermal shock and chemical corrosion</li></ul>", category_id: "1", subcategory_id:"4", vendor_id:"1")
product = Product.find(17)
product.variations.create(variation_name: "5 ml", variation_sku: "KSFE-1130/03", variation_price: "52.00")
product.variations.create(variation_name: "10 ml", variation_sku: "KSFE-1130/05M", variation_price: "36.00")
product.variations.create(variation_name: "25 ml", variation_sku: "KSFE-1130/11M", variation_price: "11.00")
product.variations.create(variation_name: "50 ml", variation_sku: "KSFE-1130/02M", variation_price: "11.00")
product.variations.create(variation_name: "100 ml", variation_sku: "KSFE-1130/06D", variation_price: "12.00")
product.variations.create(variation_name: "150 ml", variation_sku: "KSFE-1130/10D", variation_price: "14.00")
product.variations.create(variation_name: "200 ml", variation_sku: "KSFE-1130/12D", variation_price: "14.00")
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE-1130/14D", variation_price: "14.00")
product.variations.create(variation_name: "300 ml", variation_sku: "KSFE-1130/16D", variation_price: "15.00")
product.variations.create(variation_name: "500 ml", variation_sku: "KSFE-1130/20D", variation_price: "17.00")
product.variations.create(variation_name: "1000 ml", variation_sku: "KSFE-1130/26D", variation_price: "26.00")
product.variations.create(variation_name: "2000 ml", variation_sku: "KSFE-1130/30D", variation_price: "47.00")
product.variations.create(variation_name: "3000 ml", variation_sku: "KSFE-1130/32D", variation_price: "88.00")
product.variations.create(variation_name: "5000 ml", variation_sku: "KSFE-1130/46D", variation_price: "164.00")

Product.create(product_name: "Pyrex Narrow Neck Heavy Duty conical Flask", product_brand: "Pyrex", product_description: "<ul><li>Mechanically stronger than standard flasks</li><li>Designed for longer life and increased user safety</li><li>Reinforced rims to reduce chipping and breakage</li></ul>", category_id: "1", subcategory_id:"4", vendor_id: "1")
product = Product.find(18)
product.variations.create(variation_name: "10 ml", variation_sku: "KSFE-4980-10", variation_price: "25.00")
product.variations.create(variation_name: "25 ml", variation_sku: "KSFE-4980-25", variation_price: "16.00")
product.variations.create(variation_name: "50 ml", variation_sku: "KSFE-4980-50", variation_price: "15.00")
product.variations.create(variation_name: "125 ml", variation_sku: "KSFE-4980-125", variation_price: "16.00")
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE-4980-250", variation_price: "16.00")
product.variations.create(variation_name: "500 ml", variation_sku: "KSFE-4980-500", variation_price: "18.00")
product.variations.create(variation_name: "1000 ml", variation_sku: "KSFE-4980-1L", variation_price: "34.00")
product.variations.create(variation_name: "2000 ml", variation_sku: "KSFE-4980-2L", variation_price: "63.00")
product.variations.create(variation_name: "4000 ml", variation_sku: "KSFE-4980-4L", variation_price: "235.00")
product.variations.create(variation_name: "6000 ml", variation_sku: "KSFE-4980-6L", variation_price: "380.00")

Product.create(product_name: "Pyrex Wide Neck conical Flask", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 24450</li><li>Erlenmeyer pattern</li><li>Manufactured from Pyrex borosilicate glass</li><li>Excellent thermal performance</li><li>High resistance to chemical attack</li><li>White enamel graduations and marking spot</li></ul>", category_id: "1", subcategory_id:"4", vendor_id: "1")
product = Product.find(19)
product.variations.create(variation_name: "50 ml", variation_sku: "KSFE-1140/02M", variation_price: "12.00")
product.variations.create(variation_name: "100 ml", variation_sku: "KSFE-1140/04D", variation_price: "14.00")
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE-1140/08D", variation_price: "15.00")
product.variations.create(variation_name: "500 ml", variation_sku: "KSFE-1140/10D", variation_price: "18.00")
product.variations.create(variation_name: "1000 ml", variation_sku: "KSFE-1140/14D", variation_price: "29.00")
product.variations.create(variation_name: "2000 ml", variation_sku: "KSFE-1140/18D", variation_price: "50.00")


Product.create(product_name: "Pyrex Wide Neck conical Flask", product_brand: "Pyrex", product_description: "<ul><li>Mechanically stronger than conventional Erlenmeyers</li><li>Reinforced rims for extra strength and resistance to impact fracture</li><li>Manufactured from high quality Pyrex borosilicate glass</li><li>White graduations and marking spot</li></ul>", category_id: "1", subcategory_id:"4", vendor_id: "1")
product = Product.find(20)
product.variations.create(variation_name: "125 ml", variation_sku: "KSFE-5100-125", variation_price: "15.00")
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE-5100-250", variation_price: "15.00")
product.variations.create(variation_name: "500 ml", variation_sku: "KSFE-5100-500", variation_price: "19.00")
product.variations.create(variation_name: "1000 ml", variation_sku: "KSFE-5100-1L", variation_price: "35.00")
product.variations.create(variation_name: "2000 ml", variation_sku: "KSFE-5100-2L", variation_price: "70.00")

Product.create(product_name: "Pyrex Volumetric Flask Class A, Works Certified DIN/ISO/USP tolerances", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 1042 and DIN 12664</li><li>Calibrated to the tolerances required by the United States Pharmacopoeia (USP) which are tighter than those of ISO/DIN standards</li><li>Each flask engraved with inividual serial number and supplied with certificate of calibration traceable to National standards</li><li>Conformity 'H' certified</li><li>Manufactured from borosilicate glass for corrosion-free performance</li><li>White enamel inscriptions</li><li>Polyethylene stopper</li></ul>", category_id: "1", subcategory_id:"5", vendor_id: "1")
product = Product.find(21)
product.variations.create(variation_name: "1 ml", variation_sku: "KSFE-3151/01WC", variation_price: "119.00")
product.variations.create(variation_name: "2 ml", variation_sku: "KSFE-3151/02WC", variation_price: "119.00")
product.variations.create(variation_name: "5 ml", variation_sku: "KSFE-3151/04WC", variation_price: "57.00")
product.variations.create(variation_name: "10 ml", variation_sku: "KSFE-3151/06WC", variation_price: "57.00")
product.variations.create(variation_name: "20 ml", variation_sku: "KSFE-3151/08WC", variation_price: "60.00")
product.variations.create(variation_name: "25 ml", variation_sku: "KSFE-3151/10WC", variation_price: "60.00")
product.variations.create(variation_name: "50 ml", variation_sku: "KSFE-3151/12WC", variation_price: "61.00")
product.variations.create(variation_name: "100 ml", variation_sku: "KSFE-3151/14WC", variation_price: "64.00")
product.variations.create(variation_name: "200 ml", variation_sku: "KSFE-3151/16WC", variation_price: "87.00")
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE-3151/18WC", variation_price: "81.00")
product.variations.create(variation_name: "500 ml", variation_sku: "KSFE-3151/20WC", variation_price: "100.00")
product.variations.create(variation_name: "1000 ml", variation_sku: "KSFE-3151/22WC", variation_price: "135.00")
product.variations.create(variation_name: "2000 ml", variation_sku: "KSFE-3151/24WC", variation_price: "226.00")
product.variations.create(variation_name: "5000 ml", variation_sku: "KSFE-3151/26WC", variation_price: "743.00")

Product.create(product_name: "Pyrex Volumetric Flask Class A, DIN/ISO/USP tolerances", product_brand: "Pyrex", product_description: "<ul><li>Complies with ISO 1042 and DIN 12664</li><li>Calibrated to the tolerances required by the United States Pharmacopoeia (USP) which are tighter than those of ISO/DIN standards</li><li>Each flask is laser etched with inividual serial number batch code and date of manufacturer</li><li>Batch certificate available to download online</li><li>Conformity 'H' certified</li><li>Manufactured from chemically resistant pyrex glass</li><li>Inscriptions in white enamel</li><li>Polyethylene stopper</li></ul>", category_id: "1", subcategory_id:"5", vendor_id: "1")
product = Product.find(22)
product.variations.create(variation_name: "1 ml", variation_sku: "KSFE-3151/01", variation_price: "88.00")
product.variations.create(variation_name: "2 ml", variation_sku: "KSFE-3151/02", variation_price: "88.00")
product.variations.create(variation_name: "5 ml", variation_sku: "KSFE-3151/04", variation_price: "22.00")
product.variations.create(variation_name: "10 ml", variation_sku: "KSFE-3151/06", variation_price: "19.00")
product.variations.create(variation_name: "20 ml", variation_sku: "KSFE-3151/08", variation_price: "18.00")
product.variations.create(variation_name: "25 ml", variation_sku: "KSFE-3151/10", variation_price: "18.00")
product.variations.create(variation_name: "50 ml", variation_sku: "KSFE-3151/12", variation_price: "19.00")
product.variations.create(variation_name: "100 ml", variation_sku: "KSFE-3151/14", variation_price: "21.00")
product.variations.create(variation_name: "200 ml", variation_sku: "KSFE-3151/16", variation_price: "40.00")
product.variations.create(variation_name: "250 ml", variation_sku: "KSFE-3151/18", variation_price: "46.00")
product.variations.create(variation_name: "500 ml", variation_sku: "KSFE-3151/20", variation_price: "53.00")
product.variations.create(variation_name: "1000 ml", variation_sku: "KSFE-3151/22", variation_price: "76.00")
product.variations.create(variation_name: "2000 ml", variation_sku: "KSFE-3151/24", variation_price: "151.00")
product.variations.create(variation_name: "5000 ml", variation_sku: "KSFE-3151/26", variation_price: "629.00")

OrderStatus.create(order_status: "cart")
OrderStatus.create(order_status: "quote")
OrderStatus.create(order_status: "invoice")
OrderStatus.create(order_status: "delivery")










